# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Add all Slate internal pod sources for ContentEditVC dependencies
source 'https://github.com/slateteams/ios-fm-rendering'
source 'https://github.com/slateteams/ios-server-data'
source 'https://github.com/slateteams/ios-fm-sharing'
source 'https://github.com/slateteams/ios-fm-textview'
source 'https://github.com/slateteams/ios-nfl-sharing'
source 'https://github.com/slateteams/ios-fm-lib'
source 'https://github.com/slateteams/ios-nfl-football-api'
source 'https://github.com/slateteams/ios-nfl-id-api'
source 'https://github.com/slateteams/ios-app-data'
source 'https://github.com/slateteams/ios-api'
source 'https://github.com/slateteams/ios-integration-photoshelter'
source 'https://github.com/slateteams/ios-integration-slack'
source 'https://github.com/slateteams/ios-integration-getty'
source 'https://github.com/slateteams/ios-effects'
# Standard CocoaPods source for public dependencies
source 'https://cdn.cocoapods.org/'

platform :ios, '16.0'
prepare_react_native_project!

use_frameworks! :linkage => :static

target 'slateReactNative' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true,
    :fabric_enabled => true
  )

  # Using the independent SlateReactNative podspec with MBProgressHUD
  pod 'SlateReactNative', :path => '../../ios-app'

  post_install do |installer|
    # Standard React Native post-install
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Clean configuration for prebuilt framework approach
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end